import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import NavBar from "@/components/NavBar";
import { auth } from "@/app/auth";
import UserSessionProvider from "@/components/UserSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <UserSessionProvider session={session}>
            <NavBar/>         
            {children}
          </UserSessionProvider>
        </Providers>
      </body>
    </html>
  );
}

// ✅ 클라이언트 컴포넌트에서는 session을 Context로 관리